### PR TITLE
Add fixtures, and test for Link component with package json

### LINKED ISSUE #4: Edit contents on .json files
[react-static-boilerplate](https://github.com/kriasoft/react-static-boilerplate) has a `package.json` inside component folder. We need to change that as well as we do with `.css`, `.js` etc.

### PR DESCRIPTION
**Pull request by dmitrika**
Closes #4 
It works, but if we do not specify second attribute `componentName` for `getFiles` function, is that ok?

### CODE REVIEW

**Comment by dmitrika** [comment]
Huh, locally I have all test passed.
Seems, like travis has different setup.

I added fixtures by `git clone repo` in the fixtures dir, is that correct way?

**Comment by diegohaz** [comment]
@dmitrika I think you need to `rm -rf .git` inside `test/fixtures/react-static-boilerplate`. Otherwise it will be read as a git submodule.

**Comment by dmitrika** [comment]
Yeap, looks like it helped!

I didn't know it before, btw 🤓

**Comment by diegohaz** [comment]
Nice. Thank you, @dmitrika 😊

**Comment by dmitrika** [comment]
Thank you for excellent support!

**Pull request merged**
